name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        id: vercel_deploy
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            DEPLOY_URL=$(vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --confirm --prebuilt)
          else
            DEPLOY_URL=$(vercel deploy --yes --token=${{ secrets.VERCEL_TOKEN }} --confirm --prebuilt)
          fi
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
          echo "✅ Deployment URL: $DEPLOY_URL"

      - name: Show Deployment URL
        run: echo "🚀 App deployed at: ${{ env.DEPLOY_URL }}"
