name: Docker Hello World Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Run hello-world Docker image
        run: docker run hello-world

      - name: Remove hello-world Docker image
        run: docker rmi hello-world
